name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.8.0
  firebase_auth: 4.3.0
  cloud_firestore: 4.4.5
  firebase_storage: 11.0.16
  google_fonts: 4.0.3
  image_picker: 0.8.7+1
  path_provider: 2.0.14
  convex_bottom_bar: 3.2.0
  intl: 0.17.0
  geolocator: 9.0.2
  geocoding: 2.1.0
  flutter: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 2

dev_dependencies:
  flutter_launcher_icons: "^0.12.0" 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter


flutter: 
  uses-material-design: true

